### ISSUE TITLE
Badge shows coverage of wrong branch

### ISSUE THREAD

**Issue by 304NotModified** [codecov/support#191]
The badge shows the coverage of another branch.

I have:

https://codecov.io/github/NLog/NLog/coverage.svg?branch=master, which shows a few days ago 75% and now 73% (huge drop for a lot of code)
![image](https://cloud.githubusercontent.com/assets/5808377/15097161/261d58d6-1513-11e6-9867-bcac4fd9cb06.png)

When I check the dashboard:
https://codecov.io/gh/NLog/NLog/branch/master/commits

I looks like the badge shows the coverage of PR 1397 (red border), and not master (green border)

![image](https://cloud.githubusercontent.com/assets/5808377/15097175/81aa67ac-1513-11e6-93aa-d70e3d32ffca.png)

**Comment by 304NotModified** [comment]
Update: the badge shows the latest build, disregarded on which branch

I guess it sees the PR build as a master build.

**Comment by 304NotModified** [comment]
In summary, this is still an issue and broken since v4

**Comment by 304NotModified** [comment]
@stevepeak can you check this?

**Comment by nfischer** [comment]
Bumping this thread, since we saw this over at shelljs/shx#51 and shelljs/shx#52, and found no solution.

**Comment by stevepeak** [comment]
I've deployed a couple bugs in the badge recently. I believe this is fixed

**Comment by skirpichev** [comment]
@stevepeak, I believe I still see this in [my repo](https://github.com/diofant/diofant/).

Badge shows 89%, but [there is latest merge](https://codecov.io/gh/diofant/diofant/commit/5e83be9dcee428658773d0fbea4921695e52480a) with >90%.

**Comment by 304NotModified** [comment]
It looks like it shows the percentage of the lastest auto merge commit in master of a PR, but that commit isn't in master yet. 

PS didn't found the issue at my repositories, but that could be luck.

**Comment by stevepeak** [comment]
@skirpichev From what I'm gathering @304NotModified is correct about the merge commits.

The pull requests are uploaded as `branch=master pr=274`. I'm continuing to investigate on ways to resolve this.

Thank you!

**Comment by stevepeak** [comment]
I found one issue with tagging the commit as merged or not merged. This may resolve this issue. Monitoring and will report back.

**Comment by 304NotModified** [comment]
This is still broken :(  

Same case,  showing 73% suddenly.

**Comment by 304NotModified** [comment]
@stevepeak bump

**Comment by stevepeak** [comment]
Hey can you grab me a most recent `owner/repo@branch` I can review 🙇

**Comment by 304NotModified** [comment]
Too bad the example is gone for now, will report when it occurs again!

**Comment by skirpichev** [comment]
@stevepeak, here is [an example](https://github.com/diofant/diofant) right now.  It shows coverage status from the https://github.com/diofant/diofant/pull/295.

It's easy to reproduce, this happens to me every time when some travis job was killed due to timeout.

**Comment by stevepeak** [comment]
@skirpichev looks like [this commit](https://codecov.io/gh/diofant/diofant/tree/2843e8e02a9be28ba2dee0d20001d89258a78a10) is believed to be on master. However it does appear to be on a pull request. I think I'm understanding this issue and can figure it out from here. Back shortly.

**Comment by 304NotModified** [comment]
That would be nice as the badge is currently a bit useless

**Comment by stevepeak** [comment]
Update: I'm trying to figure out how to handle this. Fixing this issue causes another concerning branch tips of pull requests.

- **GOOD** If you upload a report to `pr=1 branch=feature_a` then codecov will set this commit as the head of both `pr=1` and `branch=feature_a`
- **BAD** If you upload a report to `pr=1 branch=master` then codecov will set this commit as the head of both `pr=1` and `branch=master`

In @skirpichev example this specific commit was uploaded to `pr=275 branch=master` which updated the tip of master to this commit.

----

My current thought is to not update the branch tip when `pr=X and branch="repo default"`

**Comment by nfischer** [comment]
@stevepeak It seems too me like both of those scenarios are bad. If I'm developing on branch `feature-foo-bar` for PR 1, then PR 1 and `branch=feature-foo-bar` should both show 73% coverage (because that's the branch I was on). However, if PR 1 is opened against (**but not yet merged into**) a branch called `experimental`, that shouldn't affect the status of `branch=experimental`. It doesn't matter if it's default or not: if the commit isn't on `branch=experimental`, it shouldn't affect that branch's coverage.

If it's on a non-default branch, the only difference is that it won't affect the badge, but it sounds like it'll still mess up codecov's reporting for that branch, which really is the underlying issue.

If I'm misunderstanding you, let me know. I'm new to using codecov, so I still have more to learn :smile:

**Comment by 304NotModified** [comment]
I agree with @nfischer 

Any way, it worked before. Isn't easier to look the previous code?

**Comment by stevepeak** [comment]
Patch in the pipeline 👍

**Comment by skirpichev** [comment]
It seems this doesn't fixed yet in production, right?

Now I see 55% coverage (instead of 90%) on the https://github.com/diofant/diofant.  Just as before, this is result from the latest pr https://github.com/diofant/diofant/pull/313 (one travis job wasn't finished) and not from the master.

**Comment by stevepeak** [comment]
Hey @skirpichev I'm seeing 91% here: https://codecov.io/gh/diofant/diofant/branch/master/graphs/badge.svg

Sorry I didn't catch the 55% in time.

**Comment by 304NotModified** [comment]
So this isn't fixed yet?

**Comment by stevepeak** [comment]
I do believe it is. But there could have been more than 1 necessary fix for all cases. I guess at this point waiting to hear from customers if they find issues.

**Comment by skirpichev** [comment]
> So this isn't fixed yet?

Sure, it isn't.  At least, not for me.

@stevepeak, I'm sorry, but I can't stop merging stuff to master just to show you cool picture.  But issue seems to be easily reproducible (as described above).  FYI, now it happens just for another pr: https://github.com/diofant/diofant/pull/275.

Here is some images.  Project page & badge:
![master](https://cloud.githubusercontent.com/assets/2155800/16901153/ae2a2906-4c4b-11e6-8f8b-cd6f51ce7137.png)

Pull request:
![pr](https://cloud.githubusercontent.com/assets/2155800/16901143/816e7750-4c4b-11e6-8404-d2542d979b2c.png)

Codecov project page (badge links to):
![codecov](https://cloud.githubusercontent.com/assets/2155800/16901157/e4c86be4-4c4b-11e6-816b-7cb3f017440d.png)

**Comment by mpavlov** [comment]
Confirmed this is also an issue with Github Enterprise integration. #229 should probably be closed as duplicate of #191, and #191 should be reopened.

**Comment by stevepeak** [comment]
> Thanks @mpavlov for the suggestion 👍 

Today I deployed a new query for the dashboard and badge. Looking back there were multiple reason why this issue occurred. I'm monitoring these fixes to see if we have resolved this. Thank you!

**Comment by mpavlov** [comment]
I'm unable to test the badge at the moment, but it looks like the dashboard now shows the correct branch name and coverage % for master, even after a new PR's report has been published. Nice! :)

**Comment by skirpichev** [comment]
Hmm, still doesn't work for me.

**Comment by 304NotModified** [comment]
@stevepeak maybe it's a good idea to try to reproduce this issue in your own repos?

**Comment by rockuw** [comment]
@stevepeak I got this problem too. Please help.

https://codecov.io/github/ali-sdk/ali-oss/coverage.svg?branch=master

It shows a coverage for an **unmerged PR** as the master coverage.

**Comment by 304NotModified** [comment]
Please reopen.

**Comment by rockuw** [comment]
It seems I can't. Could you reopen it for me? Thanks.

**Comment by 304NotModified** [comment]
@stevepeak Please reopen.

**Comment by stevepeak** [comment]
The new endpoint for badges is at

```diff
- https://codecov.io/github/ali-sdk/ali-oss/coverage.svg?branch=master
+ https://codecov.io/github/ali-sdk/ali-oss/branch/master/graphs/badge.svg
```

I'll review the old endpoint to see what issues I can find. Sorry for the delay here.

**Comment by stevepeak** [comment]
@rockuw your issue here concerns the branch for this commit. I'll be investigating this more. Thank you for your patience.

**Comment by rockuw** [comment]
@stevepeak Thanks. BTW, the new endpoint also fails: 
![image](https://cloud.githubusercontent.com/assets/1209779/17991838/dcd77e1e-6b74-11e6-9547-5a35b2e8e756.png)

**Comment by 304NotModified** [comment]
Confirm, this is still not fixed.

I understand this service is free for us (open source), but we are disappointed that this is still not fixed and reported multiple times as fixed. I cannot recommend this service to anyone right now...

**Comment by stevepeak** [comment]
@304NotModified Sorry you feel that way. Can you please send in another link so I may investigate again. We have done a lot of work to fix branch locations and merging.

Also what link are you using for your badge?

**Comment by stevepeak** [comment]
Closing - fixed in newer versions. Thanks
