### ISSUE TITLE
"No coverage report found for master"

### ISSUE THREAD

**Issue by pitrou** [codecov/support#244]
We haven't changed the codecov configuration lately, yet we have just got this:
https://github.com/numba/numba/pull/1965#issuecomment-230316461

Note the codecov upload seems to have worked fine:
https://travis-ci.org/numba/numba/jobs/142249738#L495-L521

**Comment by nschloe** [comment]
I'm also getting [`No coverage report found.`](https://travis-ci.org/nschloe/pyfvm/builds/149854113) as of recently for [PyFvm](https://github.com/nschloe/PyFvm).

**Comment by stevepeak** [comment]
@pitrou this is a merge commit issue that we are working on. This process is quite complex internally, but should be resolved soon. Review our draft at https://github.com/codecov/support/wiki/Merge-Commits

@nschloe this is seperate issue. looks like running `coverage xml` results in `No data to report.` which can be explained when the `.coverage` files are missing. Can you contact us in the intercom chat window in codecov to follow up?

**Comment by stevepeak** [comment]
@nschloe can you rebuild that commit? I think the issue was on our side. Thank you and sorry for the outage.

**Comment by nschloe** [comment]
@stevepeak It still happens. https://travis-ci.org/nschloe/pyfvm/builds/150279680

**Comment by stevepeak** [comment]
@nschloe ok, should be all fixed up with the recent changes to how we handle python coverage. Ping me if you find otherwise 👍

**Comment by farirat** [comment]
Hi guys, is this still issue running ?

**Comment by stevepeak** [comment]
Yes. If you are having issues please ping me some links I can review. Thanks!

**Comment by farirat** [comment]
Okay, here you go: https://travis-ci.org/jookies/jasmin/builds/160000124

**Comment by stevepeak** [comment]
I'm not seeing where codecov is called in this ci build... nowhere in the logs

**Comment by farirat** [comment]
Okay am wrong there, this project is using python's coverage and not codecov

**Comment by rwu823** [comment]
Is it fixed? I had the same issue here. Merge commit isn't working correct.

https://circleci.com/gh/cepave-f2e/vue-owl-ui/105#usage-queue/containers/1
