### ISSUE TITLE
Cannot disable comments through .codecov.yml

### ISSUE THREAD

**Issue by zmwangx** [codecov/support#293]
Hi, I'm a member of the Homebrew team.

We recently added Codecov integration to [Homebrew/brew](https://github.com/Homebrew/brew) but didn't like the resulting PR comments, so we added a [`.codecov.yml`](https://github.com/Homebrew/brew/blob/master/Library/Homebrew/test/.codecov.yml) to our repo [a day ago](https://github.com/Homebrew/brew/pull/978). According to [your wiki](https://github.com/codecov/support/wiki/Codecov-Yaml) that should have done the trick. However, we're still getting Codecov comments all over our PRs (e.g., [this one](https://github.com/Homebrew/brew/pull/1004#issuecomment-247828846)).

Could you please take a look at whether we're doing something wrong, or whether there's a detection problem on your side? Past issues like #283 and #192 seem to point to the latter. Thanks.

CC @mikemcquaid.

**Comment by stevepeak** [comment]
Hey @zmwangx the yaml location was not being respected. I've just updated it and you should see this working again. I'll review more to see what may have changed the yaml location in our cache from the current location `Library/Homebrew/test/.codecov.yml`

**Comment by zmwangx** [comment]
@stevepeak Thanks for the quick response!

**Comment by zmwangx** [comment]
Closing the issue for now. I'll reopen if we still see comments.

**Comment by zmwangx** [comment]
FYI I think we're rid of it, thanks again!

**Comment by zmwangx** [comment]
@stevepeak Sorry, I think the comments were silenced for a while but now they're popping all over again 😢

**Comment by stevepeak** [comment]
@zmwangx for some reason the yaml location keeps resetting to `codecov.yml` and not your actual location. Sorry about this issue, I'll work on it now.

**Comment by zmwangx** [comment]
@stevepeak No worries, thanks for the quick response.

**Comment by MikeMcQuaid** [comment]
Seems fixed now, should be good to close again @zmwangx. Thanks @stevepeak!

**Comment by MartinNowak** [comment]
We're still getting spurious codecov comments, even though they're disabled in our `.codecov.yml`.
See https://github.com/dlang/dmd/pull/6211 and https://github.com/dlang/dmd/blob/ab9d712ad6b6a2f59e1e4427bf1627968fc65c8c/.codecov.yml#L24.
