### ISSUE TITLE
How to configure codecov to stop failing PRs when coverage is decreased by the small value?

### ISSUE THREAD

**Issue by pwittchen** [codecov/support#351]
Hi,

I'm using codecov in Android library written in Java and I have the following question:
**How to configure codecov to stop failing PRs when coverage is decreased by the small value?**

Here I have an exemplary pull request: https://github.com/pwittchen/ReactiveNetwork/pull/153.
Here's is my `codecov.yml` file: https://github.com/pwittchen/ReactiveNetwork/blob/master/codecov.yml

As you can see, code coverage was decreased by 1.8% and I set the threshold to 20%, so I expected my PR to fail when code coverage will by decreased by 20% or more, but the PR failed anyway. My configuration does not work as I expect.

Can you show me, how can I configure codecov in my project, so it won't fail my PR every time when code coverage is decreased by the value lower than 20%?

I was trying to use solution described at https://github.com/codecov/support/issues/135#issuecomment-211495485, but with no success. Can you tell me what have I done wrong? Is this solution still valid?

I'm looking forward to your reply.

Kind Regards,
Piotr

**Comment by stevepeak** [comment]
Hey @pwittchen checkout the `threshold` setting here: https://docs.codecov.io/docs/commit-status

```yaml
coverage:
  status:
    project:
      default:
        threshold: 1%
```

Thank you!

**Comment by pwittchen** [comment]
@stevepeak Thanks for your reply, but **I have exactly what you wrote and it does not work as I expect**.
In this line: https://github.com/pwittchen/ReactiveNetwork/blob/master/codecov.yml#L21.
What is wrong with my configuration?

**Comment by stevepeak** [comment]
Can you link me to the failed commit? I'll check out logs to see if there were any issues.

PS the yaml used for the pull is the tip of the pull request.

**Comment by pwittchen** [comment]
- Here's the commit: https://github.com/pwittchen/ReactiveNetwork/commit/fe7f3848d01c10b3c21264ccc9ed9ff6fb517571
- Here's the list of the commits for the feature branch `issue-151`: https://github.com/pwittchen/ReactiveNetwork/commits/issue-151
- Here's failed PR: https://github.com/pwittchen/ReactiveNetwork/pull/153

**Comment by pwittchen** [comment]
Okay, I think I figured this out.

I needed to add the following configuration:

```yml
coverage:
  status:
    patch: true
      default:
        threshold: 20%
```

I committed this change, squashed commits and pushed them once again with force.
Now, my PR is not failed.

**Comment by romanr** [comment]
@stevepeak Please reopen this issue. You added comment and immediately closed without verifying. It is still happening to our projects.
