### ISSUE TITLE
python coverage differs from standard coverage tool

### ISSUE THREAD

**Issue by skirpichev** [codecov/support#357]
[Here](https://codecov.io/gh/diofant/diofant/compare/e97a1ee507cc66e147d92160c5c24a5cb88eb54b...ab0543bb53bc94f1037b8ad899bd4badd87b5188/diff) is an example, see one partial hit.  Locally I see 100% with the coverage  4.3.4.

Why is this?

**Comment by stevepeak** [comment]
I believe coveragepy counts partially hit branches as a full hit, not a miss (like in Codecov).

**Comment by skirpichev** [comment]
Well, [coverage.py](http://coverage.readthedocs.io/en/latest/) counts partially hit branches as partial hit.  Unless there is a bug in coverage.py of course.  (I remember, that recently, ~2-4 month ago, were fixed bugs, related to wrong partial coverage of generators.)

It's not clear what's wrong here from codecov's point of view.  Any hints?)

**Comment by stevepeak** [comment]
Maybe it is a coveragepy bug. Check this out:

```
<line branch="true" condition-coverage="-50% (-1/2)" hits="0" missing-branches="exit,60,100" number="58"/>
```

**Comment by stevepeak** [comment]
Only one upload has this

```
<line branch="true" condition-coverage="50% (1/2)" hits="1" missing-branches="100" number="58"/>
```

So branch at pos `100` is still missing. Which is what Codecov is reporting 👍 considered a miss as far as the coverage ratio is concerned.

**Comment by skirpichev** [comment]
Oh,  my bad. Ttravis run exclude xfail'ed tests, so that branch was missed indeed.  Now I see problem in local run.  Nothing wrong with codecov.  Thank you for your time.

However, line 100 - was excluded from coverage with "pragma: no cover".  In this case - one shouldn't influence on coverage hit/misses at all.  But even if I rephrase branches as
```python
if ...
elif ..
else:  # pragma: no cover
   raise NotImplementedError
``` 
I still get partial hit on elif.  Probably, there is coverage.py bug.

**Comment by skirpichev** [comment]
Indeed, with coverage 3.7.1 - I don't have partial hits.
